[2023-06-07T18:08:08.498+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [queued]>
[2023-06-07T18:08:08.513+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [queued]>
[2023-06-07T18:08:08.514+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:08:08.637+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 17:00:00+00:00
[2023-06-07T18:08:08.645+0300] {standard_task_runner.py:57} INFO - Started process 39034 to run task
[2023-06-07T18:08:08.651+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T17:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpzst3kacl']
[2023-06-07T18:08:08.655+0300] {standard_task_runner.py:85} INFO - Job 162: Subtask get_data
[2023-06-07T18:08:08.828+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:08:09.085+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T17:00:00+00:00'
[2023-06-07T18:08:15.528+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 20, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-06-07T18:08:15.559+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230606T170000, start_date=20230607T150808, end_date=20230607T150815
[2023-06-07T18:08:15.737+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 162 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 39034)
[2023-06-07T18:08:15.780+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:08:15.809+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:45:04.293+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [queued]>
[2023-06-07T18:45:04.366+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [queued]>
[2023-06-07T18:45:04.367+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:45:04.545+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 17:00:00+00:00
[2023-06-07T18:45:04.554+0300] {standard_task_runner.py:57} INFO - Started process 53652 to run task
[2023-06-07T18:45:04.570+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T17:00:00+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpete16cba']
[2023-06-07T18:45:04.574+0300] {standard_task_runner.py:85} INFO - Job 230: Subtask get_data
[2023-06-07T18:45:04.788+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:45:05.679+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T17:00:00+00:00'
[2023-06-07T18:45:05.679+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:45:05.825+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230606T170000, start_date=20230607T154504, end_date=20230607T154505
[2023-06-07T18:45:05.959+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:45:06.019+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:50:23.730+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [queued]>
[2023-06-07T18:50:23.776+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [queued]>
[2023-06-07T18:50:23.777+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:50:23.834+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 17:00:00+00:00
[2023-06-07T18:50:23.842+0300] {standard_task_runner.py:57} INFO - Started process 57962 to run task
[2023-06-07T18:50:23.861+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T17:00:00+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpsv5wc499']
[2023-06-07T18:50:23.877+0300] {standard_task_runner.py:85} INFO - Job 295: Subtask get_data
[2023-06-07T18:50:24.116+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T17:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:50:24.687+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T17:00:00+00:00'
[2023-06-07T18:50:24.688+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:50:24.725+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230606T170000, start_date=20230607T155023, end_date=20230607T155024
[2023-06-07T18:50:24.799+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:50:24.972+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
