[2023-06-07T18:07:53.187+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [queued]>
[2023-06-07T18:07:53.209+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [queued]>
[2023-06-07T18:07:53.209+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:07:53.244+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 04:00:00+00:00
[2023-06-07T18:07:53.255+0300] {standard_task_runner.py:57} INFO - Started process 38214 to run task
[2023-06-07T18:07:53.264+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T04:00:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmplhmffksd']
[2023-06-07T18:07:53.268+0300] {standard_task_runner.py:85} INFO - Job 149: Subtask get_data
[2023-06-07T18:07:53.468+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:07:53.886+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T04:00:00+00:00'
[2023-06-07T18:07:54.925+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 20, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-06-07T18:07:54.967+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230606T040000, start_date=20230607T150753, end_date=20230607T150754
[2023-06-07T18:07:55.031+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 149 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 38214)
[2023-06-07T18:07:55.122+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:07:55.349+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:44:53.833+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [queued]>
[2023-06-07T18:44:53.885+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [queued]>
[2023-06-07T18:44:53.886+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:44:53.920+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 04:00:00+00:00
[2023-06-07T18:44:53.929+0300] {standard_task_runner.py:57} INFO - Started process 52983 to run task
[2023-06-07T18:44:53.937+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T04:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpfm2hbvyy']
[2023-06-07T18:44:53.962+0300] {standard_task_runner.py:85} INFO - Job 217: Subtask get_data
[2023-06-07T18:44:54.187+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:44:54.648+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T04:00:00+00:00'
[2023-06-07T18:44:54.649+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:44:54.683+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230606T040000, start_date=20230607T154453, end_date=20230607T154454
[2023-06-07T18:44:54.731+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:44:54.781+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:50:11.910+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [queued]>
[2023-06-07T18:50:11.977+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [queued]>
[2023-06-07T18:50:11.977+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:50:12.373+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 04:00:00+00:00
[2023-06-07T18:50:12.380+0300] {standard_task_runner.py:57} INFO - Started process 57401 to run task
[2023-06-07T18:50:12.415+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T04:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpf2fgl_1o']
[2023-06-07T18:50:12.421+0300] {standard_task_runner.py:85} INFO - Job 282: Subtask get_data
[2023-06-07T18:50:12.752+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T04:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:50:13.302+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T04:00:00+00:00'
[2023-06-07T18:50:13.303+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:50:13.330+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230606T040000, start_date=20230607T155011, end_date=20230607T155013
[2023-06-07T18:50:13.392+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:50:13.434+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
